import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";
import Container from "@/components/ui/Container";
import { buttonClasses } from "@/components/ui/Button";
import ExampleTabs from "@/components/example/ExampleTabs";

const TITLE = "Example output — PlantPal specs | SpecForge";
const DESCRIPTION = "A real spec.md, tasks.md, and agents.md generated by SpecForge for a houseplant-watering app idea.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: { title: TITLE, description: DESCRIPTION, type: "website" },
};

export default function ExamplePage() {
  return (
    <>
      <Header />
      <main>
        <Container className="max-w-4xl py-16 sm:py-24">
          <span className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-3 py-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Example output
          </span>
          <h1 className="mt-6 font-display text-4xl font-semibold tracking-tight text-foreground sm:text-5xl">
            PlantPal
          </h1>
          <p className="mt-4 max-w-xl text-lg text-muted-foreground">
            A real doc set SpecForge generated from the idea: &quot;an app for apartment renters to track watering
            schedules for their houseplants.&quot; This is exactly what you get — no editing, no lorem ipsum.
          </p>
          <Link href="/create" className={buttonClasses("primary", "md", "mt-6")}>
            Generate my own specs
          </Link>

          <div className="mt-12">
            <ExampleTabs />
          </div>
        </Container>
      </main>
      <Footer />
    </>
  );
}
